import { Text, View } from 'react-native';

export default function App() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Welcome to React Native (Expo)</Text>
      <Text>Generated by Forge-Gen</Text>
    </View>
  );
}